import React, { useState, useMemo } from 'react';
import { FileText, Copy, Check, Printer, Download, RefreshCw, Calendar, TrendingUp, AlertTriangle, DollarSign, Shield, Sparkles } from 'lucide-react';
import { formatINR } from '../services/aiAgent';

export default function LeadershipBrief({ kpis, sectors, waterfall, qualityAudit, deals, workOrders, arList }) {
  const [copied, setCopied] = useState(false);
  const [activeSection, setActiveSection] = useState('full');

  if (!kpis) return null;
  const { pipeline, operations } = kpis;

  const currentDate = new Date().toLocaleDateString('en-IN', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
  });

  const topSectors = sectors.slice(0, 5);
  const topAR = arList?.slice(0, 5) || [];

  // Generate complete executive report text
  const reportMarkdown = useMemo(() => {
    return `# Executive Leadership Briefing | Skylark Drones
**Report Date**: ${currentDate}
**Data Source**: Monday.com Boards (Deals + Work Orders) | Data Quality: ${qualityAudit?.overallScore || 95}%

---

## 1. Executive Topline Summary

| Metric | Value |
|:---|:---|
| Active Sales Pipeline | ${formatINR(pipeline.totalPipelineValue)} (${pipeline.openDealsCount} deals) |
| Probability-Weighted Pipeline | ${formatINR(pipeline.weightedPipelineValue)} |
| Total Won Revenue (YTD) | ${formatINR(pipeline.totalWonValue)} (${pipeline.wonDealsCount} deals) |
| Pipeline Win Rate | ${pipeline.winRate}% |
| Total Contracted POs | ${formatINR(operations.totalWOContractValue)} (${operations.totalWOCount} WOs) |
| Total Billed Revenue | ${formatINR(operations.totalBilledValue)} (${operations.billingRealizationPct}%) |
| Cash Collected | ${formatINR(operations.totalCollectedValue)} (${operations.collectionEfficiencyPct}% efficiency) |
| Outstanding AR | ${formatINR(operations.totalAR)} |

## 2. Sectoral Performance Breakdown

| Sector | Active Pipeline | Contracted POs | Billed | Collected |
|:---|:---|:---|:---|:---|
${topSectors.map(s => `| ${s.sector} | ${formatINR(s.pipelineValue)} | ${formatINR(s.contractValue)} | ${formatINR(s.billedValue)} | ${formatINR(s.collectedValue)} |`).join('\n')}

## 3. Critical Operational Risks & Action Items

1. **Unbilled Completed Work Orders**: ${formatINR(operations.unbilledCompletedValue)} across ${operations.unbilledCompletedCount} projects awaiting invoices — immediate billing acceleration recommended.
2. **High AR Overdue Exposure**: ${formatINR(operations.priorityARTotal)} in ${operations.priorityARCount} priority accounts requiring executive escalation for collection.
3. **Data Completeness**: Monday.com board hygiene scored at ${qualityAudit?.overallScore || 95}% — ${qualityAudit?.woMissingInvoiceDate || 0} work orders missing invoice dates.

## 4. Recommendations for Leadership

- **Short Term**: Prioritize invoicing for ${operations.unbilledCompletedCount} completed projects to unlock ${formatINR(operations.unbilledCompletedValue)} in immediate revenue.
- **Medium Term**: Focus collections team on top ${operations.priorityARCount} priority AR accounts to recover ${formatINR(operations.priorityARTotal)}.
- **Strategic**: ${topSectors[0]?.sector || 'Renewables'} sector shows the strongest pipeline velocity — consider expanding BD team allocation.

---
*Auto-generated by Skylark Drones Executive BI Agent | ${currentDate}*`;
  }, [kpis, sectors, qualityAudit, arList]);

  const handleCopy = () => {
    navigator.clipboard.writeText(reportMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>Skylark Drones - Executive Leadership Brief</title>
          <style>
            body { font-family: 'Inter', -apple-system, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; color: #1a1a2e; line-height: 1.6; }
            h1 { font-size: 22px; border-bottom: 2px solid #0284c7; padding-bottom: 8px; color: #0c4a6e; }
            h2 { font-size: 16px; margin-top: 24px; color: #075985; }
            table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 13px; }
            th, td { border: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; }
            th { background: #f0f9ff; font-weight: 600; color: #0c4a6e; }
            strong { color: #0369a1; }
            hr { border: none; border-top: 1px solid #e2e8f0; margin: 20px 0; }
            em { font-size: 11px; color: #64748b; }
          </style>
        </head>
        <body>${reportMarkdown
          .replace(/# (.*)/g, '<h1>$1</h1>')
          .replace(/## (.*)/g, '<h2>$1</h2>')
          .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
          .replace(/\n---\n/g, '<hr/>')
          .replace(/\n\n/g, '<br/><br/>')
          .replace(/\n/g, '<br/>')
        }</body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-white flex items-center gap-2">
            <FileText className="w-5 h-5 text-amber-400" />
            Leadership Updates Studio
          </h2>
          <p className="text-sm text-slate-400 mt-1">Auto-generated executive briefing from live Monday.com data</p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium transition-all duration-200 ${
              copied
                ? 'bg-emerald-500/15 text-emerald-400 border border-emerald-500/20'
                : 'bg-sky-500/10 text-sky-400 border border-sky-500/20 hover:bg-sky-500/20'
            }`}
          >
            {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            {copied ? 'Copied to Clipboard!' : 'Copy Markdown'}
          </button>
          <button
            onClick={handlePrint}
            className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium bg-white/[0.06] text-slate-300 border border-white/[0.08] hover:bg-white/[0.10] transition-all"
          >
            <Printer className="w-4 h-4" />
            Print / PDF
          </button>
        </div>
      </div>

      {/* Report Preview */}
      <div className="glass-card rounded-2xl overflow-hidden">
        {/* Report Header Bar */}
        <div className="bg-gradient-to-r from-sky-600/20 via-blue-600/15 to-purple-600/10 px-6 py-4 border-b border-white/[0.06]">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-lg font-bold text-white">Executive Leadership Briefing</h3>
              <p className="text-xs text-slate-400 mt-0.5">Skylark Drones • {currentDate}</p>
            </div>
            <div className="flex items-center gap-2 text-xs">
              <div className="flex items-center gap-1 px-2.5 py-1 rounded-lg bg-emerald-500/10 text-emerald-400 border border-emerald-500/15">
                <Shield className="w-3 h-3" />
                {qualityAudit?.overallScore || 95}% Data Quality
              </div>
            </div>
          </div>
        </div>

        {/* Report Content */}
        <div className="p-6 space-y-6">
          {/* Section 1: Topline KPIs */}
          <div>
            <h4 className="text-sm font-bold text-white flex items-center gap-2 mb-3">
              <TrendingUp className="w-4 h-4 text-sky-400" />
              1. Executive Topline Summary
            </h4>
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
              {[
                { label: 'Active Pipeline', value: formatINR(pipeline.totalPipelineValue), sub: `${pipeline.openDealsCount} deals`, color: 'sky' },
                { label: 'Weighted Pipeline', value: formatINR(pipeline.weightedPipelineValue), sub: `Win rate: ${pipeline.winRate}%`, color: 'violet' },
                { label: 'Total Contracted', value: formatINR(operations.totalWOContractValue), sub: `${operations.totalWOCount} WOs`, color: 'emerald' },
                { label: 'Cash Collected', value: formatINR(operations.totalCollectedValue), sub: `${operations.collectionEfficiencyPct}% efficiency`, color: 'amber' },
              ].map((metric, i) => (
                <div key={i} className={`rounded-xl bg-${metric.color}-500/[0.06] border border-${metric.color}-500/10 p-3`}>
                  <p className={`text-lg font-bold text-${metric.color}-300`}>{metric.value}</p>
                  <p className="text-xs text-slate-400">{metric.label}</p>
                  <p className="text-[10px] text-slate-500">{metric.sub}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Section 2: Sector Table */}
          <div>
            <h4 className="text-sm font-bold text-white flex items-center gap-2 mb-3">
              <DollarSign className="w-4 h-4 text-emerald-400" />
              2. Sectoral Performance Breakdown
            </h4>
            <div className="overflow-x-auto rounded-lg border border-white/[0.06]">
              <table className="w-full text-xs">
                <thead>
                  <tr className="bg-white/[0.04]">
                    <th className="text-left px-4 py-2.5 text-slate-400 font-semibold">Sector</th>
                    <th className="text-right px-4 py-2.5 text-slate-400 font-semibold">Active Pipeline</th>
                    <th className="text-right px-4 py-2.5 text-slate-400 font-semibold">Contracted POs</th>
                    <th className="text-right px-4 py-2.5 text-slate-400 font-semibold">Billed</th>
                    <th className="text-right px-4 py-2.5 text-slate-400 font-semibold">Collected</th>
                    <th className="text-right px-4 py-2.5 text-slate-400 font-semibold">Outstanding AR</th>
                  </tr>
                </thead>
                <tbody>
                  {topSectors.map((s, i) => (
                    <tr key={i} className={`border-t border-white/[0.04] ${i % 2 === 1 ? 'bg-white/[0.015]' : ''}`}>
                      <td className="px-4 py-2.5 text-white font-medium">{s.sector}</td>
                      <td className="px-4 py-2.5 text-right text-sky-300">{formatINR(s.pipelineValue)}</td>
                      <td className="px-4 py-2.5 text-right text-blue-300">{formatINR(s.contractValue)}</td>
                      <td className="px-4 py-2.5 text-right text-emerald-300">{formatINR(s.billedValue)}</td>
                      <td className="px-4 py-2.5 text-right text-green-300">{formatINR(s.collectedValue)}</td>
                      <td className="px-4 py-2.5 text-right text-amber-300">{formatINR(s.arValue)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Section 3: Critical Risks */}
          <div>
            <h4 className="text-sm font-bold text-white flex items-center gap-2 mb-3">
              <AlertTriangle className="w-4 h-4 text-rose-400" />
              3. Critical Operational Risks & Action Items
            </h4>
            <div className="space-y-2">
              <div className="flex items-start gap-3 px-4 py-3 rounded-xl bg-rose-500/[0.06] border border-rose-500/10">
                <div className="w-6 h-6 rounded-lg bg-rose-500/20 flex items-center justify-center flex-shrink-0 mt-0.5">
                  <span className="text-xs font-bold text-rose-400">1</span>
                </div>
                <div>
                  <p className="text-sm font-medium text-white">Unbilled Completed Projects</p>
                  <p className="text-xs text-slate-400 mt-0.5">
                    <strong className="text-rose-300">{formatINR(operations.unbilledCompletedValue)}</strong> across {operations.unbilledCompletedCount} work orders have been executed but await final invoice generation. Recommend accelerating billing to unlock immediate cash flow.
                  </p>
                </div>
              </div>
              <div className="flex items-start gap-3 px-4 py-3 rounded-xl bg-amber-500/[0.06] border border-amber-500/10">
                <div className="w-6 h-6 rounded-lg bg-amber-500/20 flex items-center justify-center flex-shrink-0 mt-0.5">
                  <span className="text-xs font-bold text-amber-400">2</span>
                </div>
                <div>
                  <p className="text-sm font-medium text-white">High AR Overdue Exposure</p>
                  <p className="text-xs text-slate-400 mt-0.5">
                    <strong className="text-amber-300">{formatINR(operations.priorityARTotal)}</strong> outstanding across {operations.priorityARCount} priority accounts. Top accounts require executive escalation for collection follow-up.
                  </p>
                </div>
              </div>
              <div className="flex items-start gap-3 px-4 py-3 rounded-xl bg-blue-500/[0.06] border border-blue-500/10">
                <div className="w-6 h-6 rounded-lg bg-blue-500/20 flex items-center justify-center flex-shrink-0 mt-0.5">
                  <span className="text-xs font-bold text-blue-400">3</span>
                </div>
                <div>
                  <p className="text-sm font-medium text-white">Data Completeness Health</p>
                  <p className="text-xs text-slate-400 mt-0.5">
                    Monday.com board hygiene scored at <strong className="text-blue-300">{qualityAudit?.overallScore || 95}%</strong>. {qualityAudit?.woMissingInvoiceDate || 0} work orders are missing documented invoice dates, impacting AR computation accuracy.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Auto-gen footer */}
          <div className="flex items-center justify-between pt-4 border-t border-white/[0.06]">
            <div className="flex items-center gap-2">
              <Sparkles className="w-3.5 h-3.5 text-sky-400" />
              <span className="text-[10px] text-slate-500">Auto-generated by Skylark Executive BI Agent</span>
            </div>
            <span className="text-[10px] text-slate-500">{currentDate}</span>
          </div>
        </div>
      </div>
    </div>
  );
}
