import React, { useState, useMemo } from 'react';
import { FileText, Copy, Check, Printer, TrendingUp, AlertTriangle, DollarSign, Shield } from 'lucide-react';
import { formatINR } from '../services/aiAgent';

export default function LeadershipBrief({ kpis, sectors, qualityAudit, arList }) {
  const [copied, setCopied] = useState(false);

  if (!kpis) return null;
  const { pipeline, operations } = kpis;

  const currentDate = new Date().toLocaleDateString('en-IN', {
    weekday: 'short', year: 'numeric', month: 'short', day: 'numeric'
  });

  const topSectors = sectors.slice(0, 5);

  const reportMarkdown = useMemo(() => {
    return `# Executive Leadership Briefing | Skylark Drones
**Report Date**: ${currentDate}
**Data Source**: Monday.com Boards (Deals + Work Orders) | Data Quality: ${qualityAudit?.overallScore || 95}%

---

## 1. Executive Topline Summary

| Metric | Value |
|:---|:---|
| Active Sales Pipeline | ${formatINR(pipeline.totalPipelineValue)} (${pipeline.openDealsCount} deals) |
| Probability-Weighted Pipeline | ${formatINR(pipeline.weightedPipelineValue)} |
| Total Won Revenue (YTD) | ${formatINR(pipeline.totalWonValue)} (${pipeline.wonDealsCount} deals) |
| Pipeline Win Rate | ${pipeline.winRate}% |
| Total Contracted POs | ${formatINR(operations.totalWOContractValue)} (${operations.totalWOCount} WOs) |
| Total Billed Revenue | ${formatINR(operations.totalBilledValue)} (${operations.billingRealizationPct}%) |
| Cash Collected | ${formatINR(operations.totalCollectedValue)} (${operations.collectionEfficiencyPct}% efficiency) |
| Outstanding AR | ${formatINR(operations.totalAR)} |

## 2. Sectoral Performance Breakdown

| Sector | Active Pipeline | Contracted POs | Billed | Collected |
|:---|:---|:---|:---|:---|
${topSectors.map(s => `| ${s.sector} | ${formatINR(s.pipelineValue)} | ${formatINR(s.contractValue)} | ${formatINR(s.billedValue)} | ${formatINR(s.collectedValue)} |`).join('\n')}

## 3. Critical Operational Risks & Action Items

1. **Unbilled Completed Work Orders**: ${formatINR(operations.unbilledCompletedValue)} across ${operations.unbilledCompletedCount} projects awaiting invoices.
2. **High AR Overdue Exposure**: ${formatINR(operations.priorityARTotal)} in ${operations.priorityARCount} priority accounts requiring collection escalation.
3. **Data Completeness**: Monday.com board hygiene scored at ${qualityAudit?.overallScore || 95}%.

---
*Auto-generated by Skylark Drones Executive BI Agent | ${currentDate}*`;
  }, [kpis, sectors, qualityAudit]);

  const handleCopy = () => {
    navigator.clipboard.writeText(reportMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>Skylark Drones - Executive Leadership Brief</title>
          <style>
            body { font-family: 'Inter', -apple-system, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; color: #111; line-height: 1.6; }
            h1 { font-size: 20px; border-bottom: 2px solid #000; padding-bottom: 8px; }
            h2 { font-size: 15px; margin-top: 20px; color: #222; }
            table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 12px; }
            th, td { border: 1px solid #ddd; padding: 6px 10px; text-align: left; }
            th { background: #f4f4f5; font-weight: 600; }
            hr { border: none; border-top: 1px solid #ddd; margin: 20px 0; }
          </style>
        </head>
        <body>${reportMarkdown
          .replace(/# (.*)/g, '<h1>$1</h1>')
          .replace(/## (.*)/g, '<h2>$1</h2>')
          .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
          .replace(/\n---\n/g, '<hr/>')
          .replace(/\n\n/g, '<br/><br/>')
          .replace(/\n/g, '<br/>')
        }</body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="space-y-4 sm:space-y-6">
      {/* Header Controls */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
        <div>
          <h2 className="text-lg sm:text-xl font-bold text-white flex items-center gap-2 tracking-tight">
            <FileText className="w-4 h-4 sm:w-5 sm:h-5 text-zinc-300" />
            Leadership Updates Studio
          </h2>
          <p className="text-xs text-zinc-400 mt-0.5">1-Click executive updates generated from Monday.com boards</p>
        </div>
        <div className="flex items-center gap-2 w-full sm:w-auto">
          <button
            onClick={handleCopy}
            className={`flex-1 sm:flex-none flex items-center justify-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold transition-all ${
              copied
                ? 'bg-emerald-950 text-emerald-300 border border-emerald-800'
                : 'bg-white text-black hover:bg-zinc-200'
            }`}
          >
            {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied Markdown' : 'Copy Markdown'}</span>
          </button>
          <button
            onClick={handlePrint}
            className="flex-1 sm:flex-none flex items-center justify-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-medium bg-zinc-900 text-zinc-300 border border-zinc-800 hover:bg-zinc-800 hover:text-white transition-all"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print / PDF</span>
          </button>
        </div>
      </div>

      {/* Report Container */}
      <div className="bg-[#121215] border border-zinc-800 rounded-2xl overflow-hidden shadow-sm">
        {/* Header Bar */}
        <div className="bg-zinc-900/80 px-4 sm:px-6 py-3.5 border-b border-zinc-800 flex items-center justify-between">
          <div>
            <h3 className="text-sm font-bold text-white tracking-tight">Executive Leadership Update</h3>
            <p className="text-[10px] text-zinc-400 font-mono mt-0.5">Skylark Drones • {currentDate}</p>
          </div>
          <div className="flex items-center gap-1 px-2 py-0.5 rounded bg-zinc-800 text-zinc-300 text-[10px] font-mono border border-zinc-700">
            <Shield className="w-3 h-3 text-emerald-400" />
            {qualityAudit?.overallScore || 95}% Quality
          </div>
        </div>

        {/* Content */}
        <div className="p-4 sm:p-6 space-y-5">
          {/* Topline Grid - 2 cols on phone */}
          <div>
            <h4 className="text-xs font-bold text-zinc-200 uppercase tracking-wider flex items-center gap-1.5 mb-2.5">
              <TrendingUp className="w-3.5 h-3.5 text-zinc-400" />
              1. Topline Executive Summary
            </h4>
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-2.5 sm:gap-3">
              {[
                { label: 'Active Pipeline', value: formatINR(pipeline.totalPipelineValue), sub: `${pipeline.openDealsCount} deals` },
                { label: 'Weighted Pipeline', value: formatINR(pipeline.weightedPipelineValue), sub: `Win Rate ${pipeline.winRate}%` },
                { label: 'Contracted POs', value: formatINR(operations.totalWOContractValue), sub: `${operations.totalWOCount} WOs` },
                { label: 'Cash Collected', value: formatINR(operations.totalCollectedValue), sub: `${operations.collectionEfficiencyPct}% collected` },
              ].map((metric, i) => (
                <div key={i} className="rounded-xl bg-zinc-900/60 border border-zinc-800/80 p-3">
                  <p className="text-sm sm:text-base font-bold text-white">{metric.value}</p>
                  <p className="text-[11px] font-medium text-zinc-400 mt-0.5">{metric.label}</p>
                  <p className="text-[10px] text-zinc-500">{metric.sub}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Sector Table */}
          <div>
            <h4 className="text-xs font-bold text-zinc-200 uppercase tracking-wider flex items-center gap-1.5 mb-2.5">
              <DollarSign className="w-3.5 h-3.5 text-zinc-400" />
              2. Sectoral Performance Breakdown
            </h4>
            <div className="overflow-x-auto -mx-4 px-4 sm:mx-0 sm:px-0">
              <table className="w-full text-xs text-left min-w-[500px]">
                <thead>
                  <tr className="bg-zinc-900 border-b border-zinc-800 text-zinc-400">
                    <th className="px-3.5 py-2 font-semibold">Sector</th>
                    <th className="px-3.5 py-2 text-right font-semibold">Pipeline</th>
                    <th className="px-3.5 py-2 text-right font-semibold">Contracted POs</th>
                    <th className="px-3.5 py-2 text-right font-semibold">Billed</th>
                    <th className="px-3.5 py-2 text-right font-semibold">Collected</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-zinc-800/40">
                  {topSectors.map((s, i) => (
                    <tr key={i} className="hover:bg-zinc-900/40 transition-colors">
                      <td className="px-3.5 py-2 text-white font-medium">{s.sector}</td>
                      <td className="px-3.5 py-2 text-right text-zinc-300">{formatINR(s.pipelineValue)}</td>
                      <td className="px-3.5 py-2 text-right text-zinc-300">{formatINR(s.contractValue)}</td>
                      <td className="px-3.5 py-2 text-right text-zinc-300">{formatINR(s.billedValue)}</td>
                      <td className="px-3.5 py-2 text-right text-emerald-400 font-medium">{formatINR(s.collectedValue)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Critical Risks */}
          <div>
            <h4 className="text-xs font-bold text-zinc-200 uppercase tracking-wider flex items-center gap-1.5 mb-2.5">
              <AlertTriangle className="w-3.5 h-3.5 text-amber-400" />
              3. Critical Operational Action Items
            </h4>
            <div className="space-y-2">
              <div className="flex items-start gap-3 p-3 rounded-xl bg-zinc-900 border border-zinc-800">
                <span className="w-5 h-5 rounded bg-zinc-800 text-zinc-300 text-xs font-mono font-bold flex items-center justify-center flex-shrink-0 mt-0.5">1</span>
                <div>
                  <p className="text-xs font-semibold text-white">Unbilled Revenue Acceleration</p>
                  <p className="text-xs text-zinc-400 mt-0.5">
                    <strong className="text-white">{formatINR(operations.unbilledCompletedValue)}</strong> across {operations.unbilledCompletedCount} completed work orders await invoicing. Priority dispatch required.
                  </p>
                </div>
              </div>
              <div className="flex items-start gap-3 p-3 rounded-xl bg-zinc-900 border border-zinc-800">
                <span className="w-5 h-5 rounded bg-zinc-800 text-zinc-300 text-xs font-mono font-bold flex items-center justify-center flex-shrink-0 mt-0.5">2</span>
                <div>
                  <p className="text-xs font-semibold text-white">Overdue Accounts Receivable Recovery</p>
                  <p className="text-xs text-zinc-400 mt-0.5">
                    <strong className="text-white">{formatINR(operations.priorityARTotal)}</strong> across {operations.priorityARCount} priority client accounts requires executive follow-up.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
